# Generated by Django 5.0.7 on 2024-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_slug_alter_article_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
