# Generated by Django 5.0.7 on 2024-09-28 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_popularity_score_featuredarticle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserArticleInteraction',
            new_name='ArticleInteraction',
        ),
    ]
