# Generated by Django 5.0.7 on 2024-09-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_userarticleinteraction_articleinteraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleinteraction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AlterModelOptions(
            name='featuredarticle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Featured Article', 'verbose_name_plural': 'Featured Articles'},
        ),
    ]
