# Generated by Django 5.0.7 on 2024-09-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_articlecategory_topic_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredarticle',
            name='featured_reason',
            field=models.TextField(blank=True, choices=[('editor_choice', "Editor's Choice"), ('staff_pick', 'Staff Pick'), ('topic_highlight', 'Topic Highlight'), ('popular_article', 'Popular Article')], verbose_name='Reason for Featuring'),
        ),
    ]
