# Generated by Django 5.0.7 on 2024-09-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_featuredarticle_featured_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
    ]
