# Generated by Django 5.0.7 on 2024-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='series_sequence_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Series sequence number'),
        ),
    ]
