# Generated by Django 5.0.7 on 2024-10-30 04:11

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Paused', 'Paused'), ('Blocked', 'Blocked'), ('Waiting on Dependency', 'Waiting on Dependency')], default='Not Started', max_length=32, verbose_name='Status')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10, verbose_name='Priority')),
                ('starred', models.BooleanField(default=False, verbose_name='Starred')),
                ('icon', models.CharField(blank=True, choices=[('activity', 'activity'), ('airplay', 'airplay'), ('alert_circle', 'alert_circle'), ('alert_octagon', 'alert_octagon'), ('alert_triangle', 'alert_triangle'), ('align_center', 'align_center'), ('align_justify', 'align_justify'), ('align_left', 'align_left'), ('align_right', 'align_right'), ('anchor', 'anchor'), ('aperture', 'aperture'), ('archive', 'archive'), ('arrow_down', 'arrow_down'), ('arrow_down_circle', 'arrow_down_circle'), ('arrow_down_left', 'arrow_down_left'), ('arrow_down_right', 'arrow_down_right'), ('arrow_left', 'arrow_left'), ('arrow_left_circle', 'arrow_left_circle'), ('arrow_right', 'arrow_right'), ('arrow_right_circle', 'arrow_right_circle'), ('arrow_up', 'arrow_up'), ('arrow_up_circle', 'arrow_up_circle'), ('arrow_up_left', 'arrow_up_left'), ('arrow_up_right', 'arrow_up_right'), ('at_sign', 'at_sign'), ('award', 'award'), ('bar_chart', 'bar_chart'), ('bar_chart_2', 'bar_chart_2'), ('battery', 'battery'), ('battery_charging', 'battery_charging'), ('bell', 'bell'), ('bell_off', 'bell_off'), ('bluetooth', 'bluetooth'), ('bold', 'bold'), ('book', 'book'), ('bookmark', 'bookmark'), ('book_open', 'book_open'), ('box', 'box'), ('briefcase', 'briefcase'), ('calendar', 'calendar'), ('camera', 'camera'), ('camera_off', 'camera_off'), ('cast', 'cast'), ('check', 'check'), ('check_circle', 'check_circle'), ('check_square', 'check_square'), ('chevrons_down', 'chevrons_down'), ('chevrons_left', 'chevrons_left'), ('chevrons_right', 'chevrons_right'), ('chevrons_up', 'chevrons_up'), ('chevron_down', 'chevron_down'), ('chevron_left', 'chevron_left'), ('chevron_right', 'chevron_right'), ('chevron_up', 'chevron_up'), ('chrome', 'chrome'), ('circle', 'circle'), ('clipboard', 'clipboard'), ('clock', 'clock'), ('cloud', 'cloud'), ('cloud_drizzle', 'cloud_drizzle'), ('cloud_lightning', 'cloud_lightning'), ('cloud_off', 'cloud_off'), ('cloud_rain', 'cloud_rain'), ('cloud_snow', 'cloud_snow'), ('code', 'code'), ('codepen', 'codepen'), ('codesandbox', 'codesandbox'), ('coffee', 'coffee'), ('columns', 'columns'), ('command', 'command'), ('compass', 'compass'), ('copy', 'copy'), ('corner_down_left', 'corner_down_left'), ('corner_down_right', 'corner_down_right'), ('corner_left_down', 'corner_left_down'), ('corner_left_up', 'corner_left_up'), ('corner_right_down', 'corner_right_down'), ('corner_right_up', 'corner_right_up'), ('corner_up_left', 'corner_up_left'), ('corner_up_right', 'corner_up_right'), ('cpu', 'cpu'), ('credit_card', 'credit_card'), ('crop', 'crop'), ('crosshair', 'crosshair'), ('database', 'database'), ('delete', 'delete'), ('disc', 'disc'), ('divide', 'divide'), ('divide_circle', 'divide_circle'), ('divide_square', 'divide_square'), ('dollar_sign', 'dollar_sign'), ('download', 'download'), ('download_cloud', 'download_cloud'), ('dribbble', 'dribbble'), ('droplet', 'droplet'), ('edit', 'edit'), ('edit_2', 'edit_2'), ('edit_3', 'edit_3'), ('external_link', 'external_link'), ('eye', 'eye'), ('eye_off', 'eye_off'), ('facebook', 'facebook'), ('fast_forward', 'fast_forward'), ('feather', 'feather'), ('figma', 'figma'), ('file', 'file'), ('file_minus', 'file_minus'), ('file_plus', 'file_plus'), ('file_text', 'file_text'), ('film', 'film'), ('filter', 'filter'), ('flag', 'flag'), ('folder', 'folder'), ('folder_minus', 'folder_minus'), ('folder_plus', 'folder_plus'), ('framer', 'framer'), ('frown', 'frown'), ('gift', 'gift'), ('github', 'github'), ('gitlab', 'gitlab'), ('git_branch', 'git_branch'), ('git_commit', 'git_commit'), ('git_merge', 'git_merge'), ('git_pull_request', 'git_pull_request'), ('globe', 'globe'), ('grid', 'grid'), ('hard_drive', 'hard_drive'), ('hash', 'hash'), ('headphones', 'headphones'), ('heart', 'heart'), ('help_circle', 'help_circle'), ('hexagon', 'hexagon'), ('home', 'home'), ('image', 'image'), ('inbox', 'inbox'), ('info', 'info'), ('instagram', 'instagram'), ('italic', 'italic'), ('key', 'key'), ('layers', 'layers'), ('layout', 'layout'), ('life_buoy', 'life_buoy'), ('link', 'link'), ('linkedin', 'linkedin'), ('link_2', 'link_2'), ('list', 'list'), ('loader', 'loader'), ('lock', 'lock'), ('log_in', 'log_in'), ('log_out', 'log_out'), ('mail', 'mail'), ('map', 'map'), ('map_pin', 'map_pin'), ('maximize', 'maximize'), ('maximize_2', 'maximize_2'), ('meh', 'meh'), ('menu', 'menu'), ('message_circle', 'message_circle'), ('message_square', 'message_square'), ('mic', 'mic'), ('mic_off', 'mic_off'), ('minimize', 'minimize'), ('minimize_2', 'minimize_2'), ('minus', 'minus'), ('minus_circle', 'minus_circle'), ('minus_square', 'minus_square'), ('monitor', 'monitor'), ('moon', 'moon'), ('more_horizontal', 'more_horizontal'), ('more_vertical', 'more_vertical'), ('mouse_pointer', 'mouse_pointer'), ('move', 'move'), ('music', 'music'), ('navigation', 'navigation'), ('navigation_2', 'navigation_2'), ('octagon', 'octagon'), ('package', 'package'), ('paperclip', 'paperclip'), ('pause', 'pause'), ('pause_circle', 'pause_circle'), ('pen_tool', 'pen_tool'), ('percent', 'percent'), ('phone', 'phone'), ('phone_call', 'phone_call'), ('phone_forwarded', 'phone_forwarded'), ('phone_incoming', 'phone_incoming'), ('phone_missed', 'phone_missed'), ('phone_off', 'phone_off'), ('phone_outgoing', 'phone_outgoing'), ('pie_chart', 'pie_chart'), ('play', 'play'), ('play_circle', 'play_circle'), ('plus', 'plus'), ('plus_circle', 'plus_circle'), ('plus_square', 'plus_square'), ('pocket', 'pocket'), ('power', 'power'), ('printer', 'printer'), ('radio', 'radio'), ('refresh_ccw', 'refresh_ccw'), ('refresh_cw', 'refresh_cw'), ('repeat', 'repeat'), ('rewind', 'rewind'), ('rotate_ccw', 'rotate_ccw'), ('rotate_cw', 'rotate_cw'), ('rss', 'rss'), ('save', 'save'), ('scissors', 'scissors'), ('search', 'search'), ('send', 'send'), ('server', 'server'), ('settings', 'settings'), ('share', 'share'), ('share_2', 'share_2'), ('shield', 'shield'), ('shield_off', 'shield_off'), ('shopping_bag', 'shopping_bag'), ('shopping_cart', 'shopping_cart'), ('shuffle', 'shuffle'), ('sidebar', 'sidebar'), ('skip_back', 'skip_back'), ('skip_forward', 'skip_forward'), ('slack', 'slack'), ('slash', 'slash'), ('sliders', 'sliders'), ('smartphone', 'smartphone'), ('smile', 'smile'), ('speaker', 'speaker'), ('square', 'square'), ('star', 'star'), ('stop_circle', 'stop_circle'), ('sun', 'sun'), ('sunrise', 'sunrise'), ('sunset', 'sunset'), ('table', 'table'), ('tablet', 'tablet'), ('tag', 'tag'), ('target', 'target'), ('terminal', 'terminal'), ('thermometer', 'thermometer'), ('thumbs_down', 'thumbs_down'), ('thumbs_up', 'thumbs_up'), ('toggle_left', 'toggle_left'), ('toggle_right', 'toggle_right'), ('tool', 'tool'), ('trash', 'trash'), ('trash_2', 'trash_2'), ('trello', 'trello'), ('trending_down', 'trending_down'), ('trending_up', 'trending_up'), ('triangle', 'triangle'), ('truck', 'truck'), ('tv', 'tv'), ('twitch', 'twitch'), ('twitter', 'twitter'), ('type', 'type'), ('umbrella', 'umbrella'), ('underline', 'underline'), ('unlock', 'unlock'), ('upload', 'upload'), ('upload_cloud', 'upload_cloud'), ('user', 'user'), ('users', 'users'), ('user_check', 'user_check'), ('user_minus', 'user_minus'), ('user_plus', 'user_plus'), ('user_x', 'user_x'), ('video', 'video'), ('video_off', 'video_off'), ('voicemail', 'voicemail'), ('volume', 'volume'), ('volume_1', 'volume_1'), ('volume_2', 'volume_2'), ('volume_x', 'volume_x'), ('watch', 'watch'), ('wifi', 'wifi'), ('wifi_off', 'wifi_off'), ('wind', 'wind'), ('x', 'x'), ('x_circle', 'x_circle'), ('x_octagon', 'x_octagon'), ('x_square', 'x_square'), ('youtube', 'youtube'), ('zap', 'zap'), ('zap_off', 'zap_off'), ('zoom_in', 'zoom_in'), ('zoom_out', 'zoom_out')], default='folder', max_length=50, null=True, verbose_name='Project Icon')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('title', models.CharField(max_length=200, verbose_name='Section Title')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='arcus.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('title', models.CharField(max_length=200, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Paused', 'Paused'), ('Blocked', 'Blocked'), ('Waiting on Dependency', 'Waiting on Dependency')], default='Not Started', max_length=32, verbose_name='Status')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='arcus.task', verbose_name='Dependencies')),
                ('editor', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='arcus.task', verbose_name='Parent Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='arcus.project', verbose_name='Project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='arcus.section', verbose_name='Section')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='arcus.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['project', 'section', 'title'],
            },
        ),
    ]
