# Generated by Django 5.0.7 on 2024-10-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcus', '0003_project_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True, verbose_name='Project Icon'),
        ),
    ]
