# Generated by Django 5.0.7 on 2024-10-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcus', '0004_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, choices=[], default='folder', max_length=50, null=True, verbose_name='Project Icon'),
        ),
    ]
