# Generated by Django 5.0.7 on 2024-07-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_company_options_alter_techstack_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
