# Generated by Django 5.0.7 on 2024-07-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_project_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech_stack',
            new_name='tech_stacks',
        ),
    ]
