# Generated by Django 5.0.7 on 2024-07-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_tech_stack_project_tech_stacks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('year',)},
        ),
    ]
