# Generated by Django 5.0.7 on 2024-09-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_techstack_created_at_techstack_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='proficiency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Novice'), (2, 'Beginner'), (3, 'Competent'), (4, 'Proficient'), (5, 'Expert')], default=3, verbose_name='Proficiency'),
        ),
    ]
