# Generated by Django 5.0.7 on 2024-09-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_company_options_alter_skillcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
