# Generated by Django 5.0.7 on 2024-09-18 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_skillcategory_options_skillcategory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-proficiency', 'name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.company', verbose_name='Company'),
        ),
    ]
