# Generated by Django 5.0.7 on 2024-09-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_skill_options_alter_project_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
