# Generated by Django 5.0.7 on 2024-09-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
